name: Main
on:
  workflow_dispatch:
  schedule:
    # https://docs.github.com/en/actions/reference/events-that-trigger-workflows#schedule
    # UTC 7:00, 16:00, Sunday to Thursday. actual click randomized with sleep.
#     - cron: '0 7,16 * * 0-4'
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install
        uses: ianwalter/puppeteer@v4.0.0
        with:
          args: yarn
      - name: Run Browser
        uses: ianwalter/puppeteer@v4.0.0
        with:
          args: yarn start
        env:
          MECKANO_USER: ${{ secrets.MECKANO_USER }}
          MECKANO_PASS: ${{ secrets.MECKANO_PASS }}
      - uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: "screenshots/*"
